
package br.jus.cnj.servico_intercomunicacao_2_2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.jus.cnj.intercomunicacao_2_2.TipoAvisoComunicacaoPendente;
import br.jus.cnj.intercomunicacao_2_2.TipoCabecalhoProcesso;
import br.jus.cnj.intercomunicacao_2_2.TipoComunicacaoProcessual;
import br.jus.cnj.intercomunicacao_2_2.TipoDocumento;
import br.jus.cnj.intercomunicacao_2_2.TipoParametro;
import br.jus.cnj.intercomunicacao_2_2.TipoProcessoJudicial;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servico-intercomunicacao-2.2.2", targetNamespace = "http://www.cnj.jus.br")
@XmlSeeAlso({
    br.jus.cnj.intercomunicacao_2_2.ObjectFactory.class,
    br.jus.cnj.servico_intercomunicacao_2_2.ObjectFactory.class,
    br.jus.cnj.tipos_servico_intercomunicacao_2_2.ObjectFactory.class
})
public interface ServicoIntercomunicacao222 {


    /**
     * 
     * @param processo
     * @param documento1
     * @param mensagem
     * @param dataReferencia
     * @param senhaConsultante
     * @param incluirDocumentos
     * @param incluirCabecalho
     * @param sucesso
     * @param numeroProcesso
     * @param idConsultante
     * @param movimentos
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarProcesso")
    @RequestWrapper(localName = "consultarProcesso", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarProcesso")
    @ResponseWrapper(localName = "consultarProcessoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarProcessoResposta")
    public void consultarProcesso(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaConsultante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String numeroProcesso,
        @WebParam(name = "dataReferencia", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String dataReferencia,
        @WebParam(name = "movimentos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        Boolean movimentos,
        @WebParam(name = "incluirCabecalho", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        Boolean incluirCabecalho,
        @WebParam(name = "incluirDocumentos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        Boolean incluirDocumentos,
        @WebParam(name = "documento1", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        List<String> documento1,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem,
        @WebParam(name = "processo", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<TipoProcessoJudicial> processo);

    /**
     * 
     * @param comunicacao
     * @param mensagem
     * @param senhaConsultante
     * @param sucesso
     * @param numeroProcesso
     * @param idConsultante
     * @param identificadorAviso
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarTeorComunicacao")
    @RequestWrapper(localName = "consultarTeorComunicacao", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarTeorComunicacao")
    @ResponseWrapper(localName = "consultarTeorComunicacaoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarTeorComunicacaoResposta")
    public void consultarTeorComunicacao(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idConsultante,
        @WebParam(name = "identificadorAviso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String identificadorAviso,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String numeroProcesso,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaConsultante,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem,
        @WebParam(name = "comunicacao", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<List<TipoComunicacaoProcessual>> comunicacao);

    /**
     * 
     * @param recibo
     * @param parametros
     * @param protocoloRecebimento
     * @param senhaManifestante
     * @param dataOperacao
     * @param mensagem
     * @param parametro
     * @param dataEnvio
     * @param sucesso
     * @param documento
     * @param dadosBasicos
     * @param idManifestante
     * @param numeroProcesso
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/entregarManifestacaoProcessual")
    @RequestWrapper(localName = "entregarManifestacaoProcessual", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.EntregarManifestacaoProcessual")
    @ResponseWrapper(localName = "entregarManifestacaoProcessualResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.EntregarManifestacaoProcessualResposta")
    public void entregarManifestacaoProcessual(
        @WebParam(name = "idManifestante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idManifestante,
        @WebParam(name = "senhaManifestante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaManifestante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String numeroProcesso,
        @WebParam(name = "dadosBasicos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        TipoCabecalhoProcesso dadosBasicos,
        @WebParam(name = "documento", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        List<TipoDocumento> documento,
        @WebParam(name = "dataEnvio", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String dataEnvio,
        @WebParam(name = "parametros", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        List<TipoParametro> parametros,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem,
        @WebParam(name = "protocoloRecebimento", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> protocoloRecebimento,
        @WebParam(name = "dataOperacao", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> dataOperacao,
        @WebParam(name = "recibo", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<byte[]> recibo,
        @WebParam(name = "parametro", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<List<TipoParametro>> parametro);

    /**
     * 
     * @param mensagem
     * @param dataReferencia
     * @param senhaConsultante
     * @param sucesso
     * @param aviso
     * @param idRepresentado
     * @param idConsultante
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarAvisosPendentes")
    @RequestWrapper(localName = "consultarAvisosPendentes", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarAvisosPendentes")
    @ResponseWrapper(localName = "consultarAvisosPendentesResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarAvisosPendentesResposta")
    public void consultarAvisosPendentes(
        @WebParam(name = "idRepresentado", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idRepresentado,
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaConsultante,
        @WebParam(name = "dataReferencia", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String dataReferencia,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem,
        @WebParam(name = "aviso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<List<TipoAvisoComunicacaoPendente>> aviso);

    /**
     * 
     * @param hashDocumentos
     * @param mensagem
     * @param senhaConsultante
     * @param sucesso
     * @param hashMovimentacoes
     * @param numeroProcesso
     * @param idConsultante
     * @param hashCabecalho
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/consultarAlteracao")
    @RequestWrapper(localName = "consultarAlteracao", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarAlteracao")
    @ResponseWrapper(localName = "consultarAlteracaoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConsultarAlteracaoResposta")
    public void consultarAlteracao(
        @WebParam(name = "idConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idConsultante,
        @WebParam(name = "senhaConsultante", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaConsultante,
        @WebParam(name = "numeroProcesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String numeroProcesso,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem,
        @WebParam(name = "hashCabecalho", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> hashCabecalho,
        @WebParam(name = "hashMovimentacoes", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> hashMovimentacoes,
        @WebParam(name = "hashDocumentos", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> hashDocumentos);

    /**
     * 
     * @param mensagem
     * @param senhaRecebedor
     * @param sucesso
     * @param protocolo
     * @param idRecebedor
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/confirmarRecebimento")
    @RequestWrapper(localName = "confirmarRecebimento", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConfirmarRecebimento")
    @ResponseWrapper(localName = "confirmarRecebimentoResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", className = "br.jus.cnj.servico_intercomunicacao_2_2.ConfirmarRecebimentoResposta")
    public void confirmarRecebimento(
        @WebParam(name = "idRecebedor", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String idRecebedor,
        @WebParam(name = "senhaRecebedor", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String senhaRecebedor,
        @WebParam(name = "protocolo", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2")
        String protocolo,
        @WebParam(name = "sucesso", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<Boolean> sucesso,
        @WebParam(name = "mensagem", targetNamespace = "http://www.cnj.jus.br/tipos-servico-intercomunicacao-2.2.2", mode = WebParam.Mode.OUT)
        Holder<String> mensagem);

}
