CREATE TABLE `padrao` (
  `PADR_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador do padrão',
  `SIST_ID` INT NULL DEFAULT NULL COMMENT 'Identificador do sistema',
  `PADR_CD_PROC` VARCHAR(22) NULL DEFAULT NULL COMMENT 'Código do processo, somente números',
  `PADR_CD_USU` VARCHAR(20) NOT NULL COMMENT 'Username do usuário',
  `PADR_DF_INCLUSAO` TIMESTAMP NOT NULL COMMENT 'Timestamp da criação do padrão',
  `PADR_DF_MODIFICACAO` TIMESTAMP NOT NULL COMMENT 'Timestamp da última alteração do padrão',
  `PADR_TX_CONTEUDO` MEDIUMTEXT NOT NULL COMMENT 'Texto do padrão em formato HTML.',
  PRIMARY KEY (`PADR_ID`),
  UNIQUE INDEX `PADR_ID_UNIQUE` (`PADR_ID` ASC) VISIBLE,
  INDEX `FK_SIST_ID_idx` (`SIST_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SIST_ID`
    FOREIGN KEY (`SIST_ID`)
    REFERENCES `sistema` (`SIST_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

    UNIQUE INDEX `PADR_ID_UNIQUE` (`PADR_ID` ASC) VISIBLE;
    